# fly.toml app configuration file generated for mobslide-signaling on 2023-11-20T04:36:58+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mobslide-signaling"
primary_region = "mad"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 9000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "requests"
    soft_limit = 100000 # 100,000
    hard_limit = 100000 # 100,000